# This is a basic workflow to help you get started with Actions

name: Test Scripts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Download all Issues
        id: normalIssues
        shell: pwsh
        run: ./datenschleuder_downloader.ps1 
  bash-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2.3.1
      - name: Download all Issues
        id: normalIssues
        run: ./datenschleuder_downloader.sh
  bash-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2.3.1
      - name: Download all Issues 
        id: normalIssues
        run: ./datenschleuder_downloader.sh
